//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFarmDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSettings
    {
        public int DeviceId { get; set; }
        public Nullable<int> MoistureMin { get; set; }
        public Nullable<int> MoistureMax { get; set; }
        public Nullable<int> TemperatureMin { get; set; }
        public Nullable<int> TemperatureMax { get; set; }
        public Nullable<bool> WaterPump { get; set; }
        public Nullable<bool> AutoControl { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
