//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFarmDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int OrderId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime Time { get; set; }
        public string ManagerId { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual StatusTypes StatusTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
